### ISSUE TITLE
Large amount of data sticking around in _tempstore.chunks

### ISSUE THREAD

**Issue by zda** [CollectionFS/Meteor-cfs-tempstore#7]
My `cfs_gridfs._tempstore.chunks` collection is huge, at 1.24 GB (441 docs). Is this normal? What are the likely consequences of deleting it? 

I am pretty sure this has been the case for awhile, so most of these are probably old chunks (I don't have close to ~1 GB being actively uploaded at any given moment). 

My guess is old chunks don't matter, and the worst that happens if currently-used chunks are deleted is a file upload fails and a user has to retry it, but I thought I'd ask first.

**Comment by aldeed** [comment]
See https://github.com/CollectionFS/Meteor-CollectionFS/issues/415

**Comment by zda** [comment]
Thanks!
